# Generated by xpp/extractor/Xpp.SchemaGenerator, do not edit by hand.
#
# Source: Microsoft.Dynamics.AX.Framework.Xlnt.XppCore.dll
# from Microsoft.Dynamics.AX.Platform.CompilerPackage.
#
# Regenerate with `xpp/tools/generate-schema.sh`.

from .prelude import *


class ArraySpecification(Ast):
    index1: optional["Expression"] | child
    index2: optional["Expression"] | child

class Attribute(Ast):
    name: optional[string]
    named_parameters: list["AttributeNamedParameterEntry"] | child
    non_fully_qualified_name: optional[string]
    parameters: list["AttributeExpression"] | child

class AttributeExpression(Ast):
    literal: optional["AttributeLiteral"] | child

class AttributeList(Ast):
    attributes: list["Attribute"] | child
    contains_internal_use_only_attribute: predicate

class AttributeLiteral(Ast):
    pass

class AttributeNamedParameterEntry(XppTuple):
    item1: optional[string]
    attribute_expression: optional["AttributeExpression"] | child

class Case(Ast):
    pass

class Catch(Ast):
    pass

class ClassAccessModifier(Ast):
    class_modifiers: optional[string]

class CompilationUnit(Ast):
    comments: optional["Comment"] | child
    is_name_escaped: predicate
    name: optional[string]
    needs_transformation: predicate
    regions: list["CompilationUnitRegionEntry"] | child

class CompilationUnitRegionEntry(XppTuple):
    comment: optional["Comment"] | child
    comment2: optional["Comment"] | child

class CrossCompany(Ast):
    pass

class EvaluationActualParameterEntry(XppTuple):
    item1: predicate
    expression: optional["Expression"] | child

class Expression(Ast):
    is_const: predicate
    transformation: optional["Expression"] | child

class FieldAssignment(Ast):
    expression: optional["Expression"] | child
    extension_name: optional[string]
    field_name: optional[string]
    index: optional[int]

class FieldSpecification(Ast):
    array_index: optional["Expression"] | child
    element_type_name: optional[string]
    is_const: predicate
    is_internal: predicate
    is_private: predicate
    is_protected: predicate
    is_public: predicate
    is_read_only: predicate
    is_static: predicate
    qualifier: optional["Qualifier"] | child

class ForAssign(Ast):
    field_specification: optional["FieldSpecification"] | child

class InsertFieldSpecification(Ast):
    array_index: optional[int]
    extension_name: optional[string]
    is_extension: predicate
    name: optional[string]

class InstanceName(Ast):
    pass

class JoinSpecification(Ast):
    kind: optional[string]
    query: optional["Query"] | child

class ModelElementUsingEntry(XppTuple):
    item2: optional[string]
    item3: optional[string]

class Modifier(Ast):
    modifiers: optional[string]

class OrderElement(Ast):
    direction: optional[string]
    field: optional[string]
    index: optional[int]

class Qualifier(Ast):
    pass

class Query(Ast):
    buffer_name: optional[string]
    cross_company: optional["CrossCompany"] | child
    group_by_elements: list["OrderElement"] | child
    index_name: optional[string]
    joins: optional["JoinSpecification"] | child
    order_by_elements: list["OrderElement"] | child
    selection: optional["Selection"] | child
    selection_hints: list[string]
    uses_hint: predicate
    valid_time_state: optional["ValidTimeState"] | child
    where: optional["Expression"] | child

class QueryDataSource(Ast):
    data_sources: list["QueryDataSource"] | child
    element_type_name: optional[string]
    fetch_mode: optional[string]
    fields: list[string]
    first_fast: predicate
    first_only: predicate
    group_by: list["GlobalOrderElement"] | child
    having: list["QueryDataSourceHaving"] | child | ql.db_table_name("query_data_source_having_prop")
    join_mode: optional[string]
    name: optional[string]
    order_by: list["GlobalOrderElement"] | child
    parent_data_source: optional["QueryDataSource"] | child
    path_contribution: optional[string]
    ranges: list["QueryDataSourceRange"] | child | ql.db_table_name("query_data_source_ranges_prop")
    relations: list["QueryDataSourceRelation"] | child | ql.db_table_name("query_data_source_relations_prop")
    select_with_repeatable_read: predicate
    table: optional[string]
    update: predicate

class QueryDataSourceHaving(Ast):
    data_source_name: optional[string]
    selection: optional["SelectionField"] | child
    value: optional[string]

class QueryDataSourceRange(Ast):
    field: optional[string]
    value: optional[string]

class QueryDataSourceRelation(Ast):
    field: optional[string]
    join_data_source: optional[string]
    related_field: optional[string]

class Selection(Ast):
    pass

class SelectionField(Ast):
    extension_name: optional[string]
    field: optional[string]

class Statement(Ast):
    comments: optional[string]

class SwitchCase(Ast):
    pass

class SwitchStatementCaseEntry(XppTuple):
    case: optional["Case"] | child
    statements: list["Statement"] | child

class TableFieldReference(Ast):
    index: optional["Expression"] | child

class TryStatementCatchEntry(XppTuple):
    catch: optional["Catch"] | child
    statement: optional["Statement"] | child

class ValidTimeState(Ast):
    pass

class XppType(Ast):
    element_type_name: optional[string]
    is_obsolete: predicate

class AggregateSelection(SelectionField):
    pass

class AllFieldsSelection(Selection):
    pass

class AnyType(XppType):
    pass

class AssignmentStatement(Statement):
    pass

class BinaryExpression(Expression):
    left: optional["Expression"] | child
    right: optional["Expression"] | child

class BooleanType(XppType):
    pass

class BreakStatement(Statement):
    pass

class BreakpointStatement(Statement):
    pass

class CaseDefault(Case):
    pass

class CaseValues(Case):
    values: list["Expression"] | child

class CatchAllValues(Catch):
    pass

class CatchExpression(Catch):
    expression: optional["Expression"] | child

class CatchUpdateConflict(Catch):
    expression: optional["Expression"] | child
    instance: optional["InstanceName"] | child

class ChangeStatement(Statement):
    expression: optional["Expression"] | child
    statement: optional["Statement"] | child

class CompoundStatement(Statement):
    content: list["Statement"] | child

class ConditionalExpression(Expression):
    condition: optional["Expression"] | child
    else_part: optional["Expression"] | child
    if_part: optional["Expression"] | child

class ContainerAttributeLiteral(AttributeLiteral):
    value: list["AttributeExpression"] | child

class ContainerType(XppType):
    pass

class ContinueStatement(Statement):
    pass

class CrossCompanyAll(CrossCompany):
    pass

class CrossCompanyContainer(CrossCompany):
    container: optional["Expression"] | child

class DateTimeType(XppType):
    pass

class DateType(XppType):
    pass

class DblType(XppType):
    pass

class Declaration(CompilationUnit):
    array_specification: optional["ArraySpecification"] | child
    modifier_list: list["Modifier"] | child
    modifiers: optional[string]
    type: optional["XppType"] | child

class DefaultTypeAttributeLiteral(AttributeLiteral):
    scanned_literal_value: optional[string]

class DeleteStatement(Statement):
    query: optional["Query"] | child

class DoWhileStatement(Statement):
    condition: optional["Expression"] | child
    statement: optional["Statement"] | child

class EmptyExpression(Expression):
    pass

class EmptyStatement(Statement):
    pass

class EnumAttributeLiteral(AttributeLiteral):
    literal: optional[string]
    type_name: optional[string]

class EnumerationType(XppType):
    enumerated_type: optional[string]
    full_name: optional[string]
    namespace: optional[string]

class Evaluation(Expression):
    actual_parameters: list["EvaluationActualParameterEntry"] | child

class ExplicitSelection(Selection):
    fields: list["SelectionField"] | child

class ExpressionCompilationUnit(CompilationUnit):
    expression: optional["Expression"] | child
    path_contribution: optional[string]

class ExpressionQualifier(Qualifier):
    expression: optional["Expression"] | child

class ExpressionStatement(Statement):
    element_type_name: optional[string]
    expression: optional["Expression"] | child

class FieldExpression(Expression):
    field: optional["FieldSpecification"] | child
    is_enum: predicate

class FieldSelection(SelectionField):
    index: optional[int]

class FindStatement(Statement):
    query: optional["Query"] | child

class FlushStatement(Statement):
    id_list: list[string]

class ForDeclarationAssign(ForAssign):
    initialization_declaration: list["VariableDeclaration"] | child

class ForExpressionAssign(ForAssign):
    expression: optional["Expression"] | child

class ForFieldPostDecrement(ForAssign):
    pass

class ForFieldPostIncrement(ForAssign):
    pass

class ForFieldPreDecrement(ForAssign):
    pass

class ForFieldPreIncrement(ForAssign):
    pass

class ForStatement(Statement):
    condition: optional["Expression"] | child
    initialization: optional["ForAssign"] | child
    statement: optional["Statement"] | child
    update: optional["ForAssign"] | child

class GenericXppType(XppType):
    type_argument_list: list["XppType"] | child

class GlobalOrderElement(OrderElement):
    extension_name: optional[string]
    table: optional[string]

class GuidType(XppType):
    pass

class IfStatement(Statement):
    condition: optional["Expression"] | child
    consequent: optional["Statement"] | child

class IfThenElseStatement(Statement):
    antecedent: optional["Statement"] | child
    condition: optional["Expression"] | child
    consequent: optional["Statement"] | child

class ImplicitSelection(Selection):
    pass

class InsertStatement(Statement):
    cross_company: optional["CrossCompany"] | child
    fields: list["InsertFieldSpecification"] | child
    query: optional["Query"] | child
    table: optional[string]

class Int64Type(XppType):
    pass

class IntType(XppType):
    pass

class Intrinsic(Expression):
    arg1: optional[string]
    arg2: optional[string]
    arg3: optional[string]
    name: optional[string]

class IntrinsicAttributeLiteral(AttributeLiteral):
    arg1: optional[string]
    arg2: optional[string]
    arg3: optional[string]
    function_name: optional[string]

class IsAsExpression(Expression):
    expression: optional["Expression"] | child
    type_name: optional[string]

class LiteralExpression(Expression):
    pass

class LocalDeclarationsStatement(Statement):
    declarations: list["LocalDeclaration"] | child

class MethodOrDelegate(CompilationUnit):
    attributes: optional["AttributeList"] | child
    modifier_list: list["Modifier"] | child
    parameters: list["ParameterDeclaration"] | child
    path_contribution: optional[string]
    type: optional["XppType"] | child
    type_parameters: list[string]

class ModelElement(CompilationUnit):
    base_methods: list["MethodOrDelegate"] | child
    extend_generic_parameters: list["XppType"] | child
    full_name: optional[string]
    full_name_no_default_namespace: optional[string]
    is_internal: predicate
    is_kernel: predicate
    is_obsolete: predicate
    is_private: predicate
    is_public: predicate
    methods: list["MethodOrDelegate"] | child
    model_id: optional[int]
    modifier_list: list["ClassAccessModifier"] | child
    modifiers: optional[string]
    namespace: optional[string]
    nested_classes: list["ClassOrInterface"] | child
    path_contribution: optional[string]
    type_parameters: list[string]
    using: list["ModelElementUsingEntry"] | child
    visibility: optional[string]

class MoveCursorStatement(Statement):
    selection: optional["Selection"] | child
    table: optional[string]

class NamedFieldReference(TableFieldReference):
    extension_name: optional[string]
    field_name: optional[string]

class NewClrArrayExpression(Expression):
    full_name: optional[string]
    rectangular_dimensions: list[int]
    sizes: list["Expression"] | child
    type_argument_list: list["XppType"] | child

class NumberedFieldReference(TableFieldReference):
    field_number: optional["Expression"] | child

class Placeholder(Expression):
    pass

class PrintStatement(Statement):
    expressions: list["Expression"] | child

class ProvidedType(XppType):
    argument_list: list["Expression"] | child
    name: optional[string]

class QualifiedField(FieldSpecification):
    extension_name: optional[string]
    name: optional[string]

class QualifiedInstanceName(InstanceName):
    index: optional["Expression"] | child
    name: optional[string]
    qualifier: optional["Qualifier"] | child

class QualifiedNumberedField(FieldSpecification):
    field_number: optional["Expression"] | child

class QualifiedStaticField(FieldSpecification):
    class_name: optional[string]
    is_enum: predicate
    name: optional[string]

class RetryStatement(Statement):
    pass

class ReturnStatement(Statement):
    expression: optional["Expression"] | child

class SearchStatement(Statement):
    query: optional["Query"] | child
    statement: optional["Statement"] | child

class SimpleField(FieldSpecification):
    extension_name: optional[string]
    is_name_escaped: predicate
    name: optional[string]

class SimpleInstanceName(InstanceName):
    index: optional["Expression"] | child
    name: optional[string]

class SimpleOrderElement(OrderElement):
    extension_name: optional[string]

class SimpleQualifier(Qualifier):
    name: optional[string]

class StaticField(FieldSpecification):
    class_name: optional[string]
    name: optional[string]

class StringType(XppType):
    pass

class SwitchStatement(Statement):
    cases: list["SwitchStatementCaseEntry"] | child
    selector: optional["Expression"] | child

class TableLookupExpression(Expression):
    field: optional["TableFieldReference"] | child
    query: optional["Query"] | child

class ThrowStatement(Statement):
    exception: optional["Expression"] | child

class TryStatement(Statement):
    catches: list["TryStatementCatchEntry"] | child
    finally_: optional["Statement"] | child
    statement: optional["Statement"] | child

class TtsStatement(Statement):
    pass

class UnaryExpression(Expression):
    expression: optional["Expression"] | child

class UncheckedStatement(Statement):
    expression: optional["Expression"] | child
    statement: optional["Statement"] | child

class UpdateStatement(Statement):
    cross_company: optional["CrossCompany"] | child
    field_assignments: list["FieldAssignment"] | child
    hints: list[string]
    joins: optional["JoinSpecification"] | child
    table: optional[string]
    where: optional["Expression"] | child

class UsingStatement(Statement):
    disposable_object_initializers: list["VariableDeclaration"] | child
    statement: optional["Statement"] | child

class ValidTimeStateDate(ValidTimeState):
    date_variable: optional[string]

class ValidTimeStateRange(ValidTimeState):
    from_date_variable: optional[string]
    to_date_variable: optional[string]

class VarType(XppType):
    pass

class VoidType(XppType):
    pass

class WhileStatement(Statement):
    condition: optional["Expression"] | child
    statement: optional["Statement"] | child

class XppTypeCompilationUnit(CompilationUnit):
    type: optional["XppType"] | child

class AddExpression(BinaryExpression):
    pass

class AndExpression(BinaryExpression):
    pass

class AsClrExpression(IsAsExpression):
    pass

class AsExpression(IsAsExpression):
    pass

class AssignMultipleFieldStatement(AssignmentStatement):
    expression: optional["Expression"] | child
    fields: list["FieldSpecification"] | child

class AssignmentSingleField(AssignmentStatement):
    field: optional["FieldSpecification"] | child

class AvgAggregateSelection(AggregateSelection):
    pass

class BooleanAttributeLiteral(DefaultTypeAttributeLiteral):
    pass

class ChangeCompanyStatement(ChangeStatement):
    pass

class ClassOrInterface(ModelElement):
    attributes: optional["AttributeList"] | child
    element_type_name: optional[string]
    enclosing_type: optional["ModelElement"] | child
    extends: optional[string]
    is_abstract: predicate
    is_composite_data_entity_view: predicate
    is_final: predicate
    is_nested: predicate
    is_static: predicate
    qualifier: optional[string]

class ClrEnumerationLiteralExpression(LiteralExpression):
    enumeration_literal: optional[string]
    enumeration_type: optional[string]

class ClrType(GenericXppType):
    full_name: optional[string]
    rectangular_dimensions: list[int]

class ContainerLiteralExpression(LiteralExpression):
    value: list["Expression"] | child

class CountAggregateSelection(AggregateSelection):
    pass

class DateAttributeLiteral(DefaultTypeAttributeLiteral):
    pass

class DateTimeAttributeLiteral(DefaultTypeAttributeLiteral):
    pass

class DblAttributeLiteral(DefaultTypeAttributeLiteral):
    pass

class DefaultTypeLiteralExpression(LiteralExpression):
    scanned_literal_value: optional[string]

class Delegate(MethodOrDelegate):
    is_static: predicate

class DivideExpression(BinaryExpression):
    pass

class EnumerationLiteralExpression(LiteralExpression):
    enumeration_literal: optional[string]
    enumeration_type: optional[string]

class FieldDeclaration(Declaration):
    attributes: optional["AttributeList"] | child
    element_type_name: optional[string]
    extension_name: optional[string]
    initial_value: optional["Expression"] | child
    is_const: predicate
    is_extension: predicate
    is_internal: predicate
    is_obsolete: predicate
    is_private: predicate
    is_protected: predicate
    is_public: predicate
    is_read_only: predicate
    is_static: predicate

class FieldExpressionInternal(FieldExpression):
    pass

class ForFieldAssign(ForExpressionAssign):
    pass

class ForFieldDecrementAssign(ForExpressionAssign):
    pass

class ForFieldIncrementAssign(ForExpressionAssign):
    pass

class FormModelElement(ModelElement):
    behavior: optional["Class"] | child
    controls: list["FormControl"] | child
    data_sources: list["FormDataSource"] | child
    element_type_name: optional[string]
    full_type_name: optional[string]

class FormNestedElement(ModelElement):
    form: optional["FormModelElement"] | child

class GenericEvaluation(Evaluation):
    type_argument_list: list["XppType"] | child

class GuidAttributeLiteral(DefaultTypeAttributeLiteral):
    pass

class InExpression(BinaryExpression):
    pass

class Int64AttributeLiteral(DefaultTypeAttributeLiteral):
    pass

class IntAttributeLiteral(DefaultTypeAttributeLiteral):
    pass

class IntegerDivideExpression(BinaryExpression):
    pass

class IsClrExpression(IsAsExpression):
    pass

class IsExpression(IsAsExpression):
    pass

class LocalDeclaration(Declaration):
    pass

class MaxAggregateSelection(AggregateSelection):
    pass

class Method(MethodOrDelegate):
    declarations_and_statements: list["Statement"] | child
    has_local_functions: predicate
    is_abstract: predicate
    is_client: predicate
    is_constructor: predicate
    is_display: predicate
    is_edit: predicate
    is_explicit_non_hookable: predicate
    is_explicit_non_wrappable: predicate
    is_extended_method: predicate
    is_final: predicate
    is_hookable: predicate
    is_hookable_on_chain_of_command: predicate
    is_internal: predicate
    is_private: predicate
    is_protected: predicate
    is_public: predicate
    is_replaceable: predicate
    is_server: predicate
    is_static: predicate
    is_type_initializer: predicate
    is_wrappable: predicate
    locals: list["LocalDeclaration"] | child
    modifiers: optional[string]
    statements: list["Statement"] | child

class MinAggregateSelection(AggregateSelection):
    pass

class ModExpression(BinaryExpression):
    pass

class MultiplyExpression(BinaryExpression):
    pass

class NamedType(GenericXppType):
    name: optional[string]

class NewCall(Evaluation):
    type: optional["XppType"] | child

class NextExpression(Evaluation):
    name: optional[string]

class NotExpression(UnaryExpression):
    pass

class NullLiteralExpression(LiteralExpression):
    pass

class OrExpression(BinaryExpression):
    pass

class PhysicalAndExpression(BinaryExpression):
    pass

class PhysicalNotExpression(UnaryExpression):
    pass

class PhysicalOrExpression(BinaryExpression):
    pass

class PhysicalXorExpression(BinaryExpression):
    pass

class ProvidedTypeStaticCall(Evaluation):
    method_name: optional[string]
    provided_type: optional["ProvidedType"] | child

class QualifiedStaticFieldExpression(FieldExpression):
    class_name: optional[string]
    is_static: predicate
    name: optional[string]

class QueryModelElement(ModelElement):
    allow_cross_company: predicate
    behavior: optional["Class"] | child
    data_source_list: list["QueryDataSource"] | child
    data_sources: list["QueryDataSource"] | child
    element_type_name: optional[string]
    user_update: predicate

class RelationalExpression(BinaryExpression):
    operator: optional[string]

class ShiftLeftExpression(BinaryExpression):
    pass

class ShiftRightExpression(BinaryExpression):
    pass

class SimpleQualifierInternal(SimpleQualifier):
    pass

class StaticQualifier(SimpleQualifier):
    class_type_argument_list: list["XppType"] | child

class StringAttributeLiteral(DefaultTypeAttributeLiteral):
    pass

class StringLengthType(StringType):
    edt_name: optional[string]
    is_edt: predicate
    length: optional[int]

class StringTypeInternal(StringType):
    pass

class SubtractExpression(BinaryExpression):
    pass

class SumAggregateSelection(AggregateSelection):
    pass

class SuperCall(Evaluation):
    pass

class Table(ModelElement):
    attributes: optional["AttributeList"] | child
    element_type_name: optional[string]
    extends: optional[string]
    fields: list["FieldDeclaration"] | child
    indexes: list[string]
    is_aggregate_data_entity: predicate
    is_data_entity_view: predicate
    is_map: predicate
    is_updatable: predicate
    is_view: predicate
    support_inheritance: predicate

class TtsAbortStatement(TtsStatement):
    pass

class TtsBeginStatement(TtsStatement):
    pass

class TtsEndStatement(TtsStatement):
    pass

class UnaryMinusExpression(UnaryExpression):
    pass

class AssignPostDecrementStatement(AssignmentSingleField):
    pass

class AssignPostIncrementStatement(AssignmentSingleField):
    pass

class AssignPreDecrementStatement(AssignmentSingleField):
    pass

class AssignPreIncrementStatement(AssignmentSingleField):
    pass

class AssignmentBinary(AssignmentSingleField):
    expression: optional["Expression"] | child

class AssignmentEventHandlerBase(AssignmentSingleField):
    addition: predicate
    name: optional[string]

class BooleanLiteralExpression(DefaultTypeLiteralExpression):
    pass

class Class(ClassOrInterface):
    fields: list["FieldDeclaration"] | child
    has_cyclic_inheritance: predicate
    implements: list[string]

class DateLiteralExpression(DefaultTypeLiteralExpression):
    pass

class DateTimeLiteralExpression(DefaultTypeLiteralExpression):
    pass

class EqualExpression(RelationalExpression):
    pass

class FieldDeclarationInternal(FieldDeclaration):
    pass

class FormControl(FormNestedElement):
    auto_declaration: predicate
    child_controls: list["FormControl"] | child
    control_class: optional[string]
    control_type: optional[string]
    custom_control_class: optional[string]
    element_type_name: optional[string]
    internal_control_name: optional[string]
    is_form_control_extension: predicate
    parent_control: optional["FormControl"] | child

class FormDataField(FormNestedElement):
    element_type_name: optional[string]
    form_data_source: optional["FormDataSource"] | child

class FormDataSource(FormNestedElement):
    data_fields: list["FormDataField"] | child
    element_type_name: optional[string]
    join_source: optional[string]
    link_type: optional[string]
    nested_data_source: predicate
    query: optional["QueryModelElement"] | child
    query_name: optional[string]
    table: optional[string]

class FormElementType(NamedType):
    form_name: optional[string]

class FunctionCall(GenericEvaluation):
    function_name: optional[string]

class FunctionDeclaration(LocalDeclaration):
    declarations_and_statements: list["Statement"] | child
    element_type_name: optional[string]
    locals: list["LocalDeclaration"] | child
    parameters: list["ParameterDeclaration"] | child
    statements: list["Statement"] | child

class GreaterThanExpression(RelationalExpression):
    pass

class GreaterThanOrEqualExpression(RelationalExpression):
    pass

class Int64LiteralExpression(DefaultTypeLiteralExpression):
    pass

class IntLiteralExpression(DefaultTypeLiteralExpression):
    pass

class Interface(ClassOrInterface):
    pass

class LessThanExpression(RelationalExpression):
    pass

class LessThanOrEqualExpression(RelationalExpression):
    pass

class LikeExpression(RelationalExpression):
    pass

class NamedTypeInternal(NamedType):
    pass

class NewClrCall(GenericEvaluation):
    clr_class_name: optional[string]

class NotEqualExpression(RelationalExpression):
    pass

class QualifiedCall(GenericEvaluation):
    method_name: optional[string]
    qualifier: optional["Qualifier"] | child

class QualifiedStaticCall(GenericEvaluation):
    class_name: optional[string]
    class_type_argument_list: list["XppType"] | child
    is_table_map_call: predicate
    method_name: optional[string]
    qualifier: optional["Qualifier"] | child

class RealLiteralExpression(DefaultTypeLiteralExpression):
    pass

class StaticMethodCall(GenericEvaluation):
    class_name: optional[string]
    class_type_argument_list: list["XppType"] | child
    method_name: optional[string]

class StringLiteralExpression(DefaultTypeLiteralExpression):
    is_label: predicate
    label_file_id: optional[string]
    label_id: optional[string]

class TableFieldDeclaration(FieldDeclaration):
    pass

class VariableDeclaration(LocalDeclaration):
    element_type_name: optional[string]
    initial_value: optional["Expression"] | child
    is_const: predicate

class AssignDecrementStatement(AssignmentBinary):
    pass

class AssignDivideStatement(AssignmentBinary):
    pass

class AssignEqualStatement(AssignmentBinary):
    pass

class AssignIncrementStatement(AssignmentBinary):
    pass

class AssignMultiplyStatement(AssignmentBinary):
    pass

class AssignmentEventHandlerInstance(AssignmentEventHandlerBase):
    qualifier_part: optional["Qualifier"] | child

class AssignmentEventHandlerStatic(AssignmentEventHandlerBase):
    type_name: optional[string]

class ParameterDeclaration(VariableDeclaration):
    is_by_ref: predicate
    is_optional: predicate

class VariableDeclarationInternal(VariableDeclaration):
    pass

class AssignmentEventHandlerClr(AssignmentEventHandlerStatic):
    pass

class AssignmentEventHandlerStaticInternal(AssignmentEventHandlerStatic):
    pass
