// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AllFieldsSelection`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.AllFieldsSelection

/**
 * INTERNAL: This module contains the customizable definition of `AllFieldsSelection` and should not
 * be referenced directly.
 */
module Impl {
  class AllFieldsSelection extends Generated::AllFieldsSelection { }
}
