// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AssignmentEventHandlerBase`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.AssignmentEventHandlerBase

/**
 * INTERNAL: This module contains the customizable definition of `AssignmentEventHandlerBase` and should not
 * be referenced directly.
 */
module Impl {
  class AssignmentEventHandlerBase extends Generated::AssignmentEventHandlerBase { }
}
