// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AssignPreDecrementStatement`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.AssignPreDecrementStatement

/**
 * INTERNAL: This module contains the customizable definition of `AssignPreDecrementStatement` and should not
 * be referenced directly.
 */
module Impl {
  class AssignPreDecrementStatement extends Generated::AssignPreDecrementStatement { }
}
