// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Ast`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.Ast

/**
 * INTERNAL: This module contains the customizable definition of `Ast` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * Root of the X++ abstract syntax tree.
   *
   * This mirrors `Microsoft.Dynamics.AX.Metadata.XppCompiler.Ast`, the base class of the
   * X++ compiler's own AST.
   */
  class Ast extends Generated::Ast { }
}
