// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BooleanLiteralExpression`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.BooleanLiteralExpression

/**
 * INTERNAL: This module contains the customizable definition of `BooleanLiteralExpression` and should not
 * be referenced directly.
 */
module Impl {
  class BooleanLiteralExpression extends Generated::BooleanLiteralExpression { }
}
