// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 *  This module defines the hook used internally to tweak the characteristic predicate of
 *  `CatchUpdateConflict` synthesized instances.
 *  INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.Raw

/**
 *  The characteristic predicate of `CatchUpdateConflict` synthesized instances.
 *  INTERNAL: Do not use.
 */
predicate constructCatchUpdateConflict(Raw::CatchUpdateConflict id) { any() }
