// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `CatchUpdateConflict`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.CatchUpdateConflict

/**
 * INTERNAL: This module contains the customizable definition of `CatchUpdateConflict` and should not
 * be referenced directly.
 */
module Impl {
  class CatchUpdateConflict extends Generated::CatchUpdateConflict { }
}
