// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `DateAttributeLiteral`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.DateAttributeLiteral

/**
 * INTERNAL: This module contains the customizable definition of `DateAttributeLiteral` and should not
 * be referenced directly.
 */
module Impl {
  class DateAttributeLiteral extends Generated::DateAttributeLiteral { }
}
