// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Delegate`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.Delegate

/**
 * INTERNAL: This module contains the customizable definition of `Delegate` and should not
 * be referenced directly.
 */
module Impl {
  class Delegate extends Generated::Delegate { }
}
