// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ExpressionStatement`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.ExpressionStatement

/**
 * INTERNAL: This module contains the customizable definition of `ExpressionStatement` and should not
 * be referenced directly.
 */
module Impl {
  class ExpressionStatement extends Generated::ExpressionStatement { }
}
