// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ForFieldPreIncrement`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.ForFieldPreIncrement

/**
 * INTERNAL: This module contains the customizable definition of `ForFieldPreIncrement` and should not
 * be referenced directly.
 */
module Impl {
  class ForFieldPreIncrement extends Generated::ForFieldPreIncrement { }
}
