// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Int64Type`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.Int64Type

/**
 * INTERNAL: This module contains the customizable definition of `Int64Type` and should not
 * be referenced directly.
 */
module Impl {
  class Int64Type extends Generated::Int64Type { }
}
