// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Int64AttributeLiteral`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.Int64AttributeLiteral

/**
 * INTERNAL: This module contains the customizable definition of `Int64AttributeLiteral` and should not
 * be referenced directly.
 */
module Impl {
  class Int64AttributeLiteral extends Generated::Int64AttributeLiteral { }
}
