// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 *  This module defines the hook used internally to tweak the characteristic predicate of
 *  `Int64LiteralExpression` synthesized instances.
 *  INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.Raw

/**
 *  The characteristic predicate of `Int64LiteralExpression` synthesized instances.
 *  INTERNAL: Do not use.
 */
predicate constructInt64LiteralExpression(Raw::Int64LiteralExpression id) { any() }
