// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `IntrinsicAttributeLiteral`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.IntrinsicAttributeLiteral

/**
 * INTERNAL: This module contains the customizable definition of `IntrinsicAttributeLiteral` and should not
 * be referenced directly.
 */
module Impl {
  class IntrinsicAttributeLiteral extends Generated::IntrinsicAttributeLiteral { }
}
