// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `LikeExpression`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.LikeExpression

/**
 * INTERNAL: This module contains the customizable definition of `LikeExpression` and should not
 * be referenced directly.
 */
module Impl {
  class LikeExpression extends Generated::LikeExpression { }
}
