// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ModelElementUsingEntry`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.ModelElementUsingEntry

/**
 * INTERNAL: This module contains the customizable definition of `ModelElementUsingEntry` and should not
 * be referenced directly.
 */
module Impl {
  class ModelElementUsingEntry extends Generated::ModelElementUsingEntry { }
}
