// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `QualifiedStaticCall`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.QualifiedStaticCall

/**
 * INTERNAL: This module contains the customizable definition of `QualifiedStaticCall` and should not
 * be referenced directly.
 */
module Impl {
  class QualifiedStaticCall extends Generated::QualifiedStaticCall { }
}
