// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `UnspecifiedElement`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.UnspecifiedElement

/**
 * INTERNAL: This module contains the customizable definition of `UnspecifiedElement` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A node that could not be extracted, for example because of a syntax error.
   */
  class UnspecifiedElement extends Generated::UnspecifiedElement { }
}
