// generated by xpp/tools/generate-schema.sh, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `XppTuple`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.xpp.elements.internal.generated.XppTuple

/**
 * INTERNAL: This module contains the customizable definition of `XppTuple` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * Base of the classes standing in for tuples in the compiler's AST.
   *
   * The X++ compiler uses CLR tuples for a handful of grouped values, such as a `catch`
   * together with its handler body. The schema has no tuple type, so the generator emits a
   * named class per tuple-valued property instead.
   */
  class XppTuple extends Generated::XppTuple { }
}
