namespace Xpp.SchemaGenerator;

/// <summary>
/// Renders an <see cref="AstModel"/> as the Python schema module consumed by
/// <c>misc/codegen</c>.
/// </summary>
public static class SchemaWriter
{
    /// <summary>Reserved words that cannot be used bare as schema property names.</summary>
    private static readonly HashSet<string> PythonKeywords = new(StringComparer.Ordinal)
    {
        "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del",
        "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in",
        "is", "lambda", "none", "nonlocal", "not", "or", "pass", "raise", "return", "try",
        "while", "with", "yield",
    };

    /// <summary>
    /// Names defined by the schema prelude or by <c>schemadefs</c> that a property must not
    /// shadow.
    /// </summary>
    private static readonly HashSet<string> ReservedNames = new(StringComparer.Ordinal)
    {
        "int", "string", "boolean", "predicate", "optional", "list", "set", "child", "synth",
    };

    /// <summary>
    /// Names supplied by the hand-written prelude. Generated classes may derive from these
    /// without the generator emitting them.
    /// </summary>
    private static readonly HashSet<string> PreludeTypes = new(StringComparer.Ordinal)
    {
        "Element", "File", "Location", "Locatable", "ErrorElement", "UnspecifiedElement",
        "Comment", "Ast", "XppTuple",
    };

    public static string Render(AstModel model)
    {
        var writer = new StringWriter();

        writer.WriteLine("# Generated by xpp/extractor/Xpp.SchemaGenerator, do not edit by hand.");
        writer.WriteLine("#");
        writer.WriteLine("# Source: Microsoft.Dynamics.AX.Framework.Xlnt.XppCore.dll");
        writer.WriteLine("# from Microsoft.Dynamics.AX.Platform.CompilerPackage.");
        writer.WriteLine("#");
        writer.WriteLine("# Regenerate with `xpp/tools/generate-schema.sh`.");
        writer.WriteLine();
        writer.WriteLine("from .prelude import *");
        writer.WriteLine();

        foreach (var type in InDefinitionOrder(model.Types))
        {
            writer.WriteLine();
            writer.WriteLine($"class {type.Name}({type.BaseName}):");

            if (type.Properties.Count == 0)
            {
                writer.WriteLine("    pass");
                continue;
            }

            foreach (var property in type.Properties)
                writer.WriteLine($"    {RenderProperty(property)}");
        }

        return writer.ToString();
    }

    /// <summary>
    /// Orders types so that every class is emitted after its base, which Python requires. Ties
    /// are broken alphabetically so the output is stable across runs.
    /// </summary>
    private static IEnumerable<AstType> InDefinitionOrder(IReadOnlyList<AstType> types)
    {
        var pending = types.OrderBy(t => t.Name, StringComparer.Ordinal).ToList();
        var emitted = new HashSet<string>(PreludeTypes, StringComparer.Ordinal);
        var ordered = new List<AstType>(pending.Count);

        while (pending.Count > 0)
        {
            var ready = pending.Where(t => t.BaseName is null || emitted.Contains(t.BaseName)).ToList();
            if (ready.Count == 0)
            {
                // A cycle, or a base that is neither generated nor in the prelude. Emitting the
                // remainder keeps the failure visible in the generated file rather than here.
                ordered.AddRange(pending);
                break;
            }

            foreach (var type in ready)
            {
                ordered.Add(type);
                emitted.Add(type.Name);
                pending.Remove(type);
            }
        }

        return ordered;
    }

    private static string RenderProperty(AstProperty property)
    {
        var name = SafeName(property.SchemaName);

        var rendered = property.Kind switch
        {
            PropertyKind.Child => $"{name}: optional[\"{property.TypeName}\"] | child",
            PropertyKind.ChildList => $"{name}: list[\"{property.TypeName}\"] | child",
            PropertyKind.String => $"{name}: optional[string]",
            PropertyKind.StringList => $"{name}: list[string]",
            PropertyKind.Boolean => $"{name}: predicate",
            PropertyKind.Int => $"{name}: optional[int]",
            PropertyKind.IntList => $"{name}: list[int]",
            // Enums are recorded by member name so the schema does not depend on numeric
            // values that can shift between platform releases.
            PropertyKind.Enum => $"{name}: optional[string]",
            PropertyKind.EnumList => $"{name}: list[string]",
            _ => throw new InvalidOperationException(
                $"cannot render skipped property {property.ClrName}"),
        };

        return property.TableName is null
            ? rendered
            : $"{rendered} | ql.db_table_name(\"{property.TableName}\")";
    }

    private static string SafeName(string name) =>
        PythonKeywords.Contains(name) || ReservedNames.Contains(name) ? name + "_" : name;

    /// <summary>A human-readable report of the model, used to review generator coverage.</summary>
    public static string RenderReport(AstModel model)
    {
        var writer = new StringWriter();

        writer.WriteLine($"types: {model.Types.Count}");
        writer.WriteLine($"abstract: {model.Types.Count(t => t.IsAbstract)}");
        writer.WriteLine($"properties: {model.Types.Sum(t => t.Properties.Count)}");
        writer.WriteLine();

        foreach (var group in model.Types
                     .SelectMany(t => t.Properties)
                     .GroupBy(p => p.Kind)
                     .OrderByDescending(g => g.Count()))
        {
            writer.WriteLine($"  {group.Count(),5}  {group.Key}");
        }

        if (model.Diagnostics.Count > 0)
        {
            writer.WriteLine();
            writer.WriteLine($"diagnostics: {model.Diagnostics.Count}");
            foreach (var group in model.Diagnostics.GroupBy(d => d.Split(": ").Last())
                         .OrderByDescending(g => g.Count()))
            {
                writer.WriteLine($"  {group.Count(),5}  {group.Key}");
                foreach (var item in group.Take(5))
                    writer.WriteLine($"           {item}");
            }
        }

        return writer.ToString();
    }
}
