# configuration file for X++ code generation default options
--schema=schema
--generate=dbscheme,ql
--dbscheme=ql/lib/xpp.dbscheme
--ql-output=ql/lib/codeql/xpp/elements/internal/generated
--ql-stub-output=ql/lib/codeql/xpp/elements
--script-name=xpp/tools/generate-schema.sh
