// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AddExpression`.
 */

private import internal.AddExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class AddExpression = Impl::AddExpression;
