// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AggregateSelection`.
 */

private import internal.AggregateSelectionImpl
import codeql.xpp.elements.SelectionField

final class AggregateSelection = Impl::AggregateSelection;
