// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AllFieldsSelection`.
 */

private import internal.AllFieldsSelectionImpl
import codeql.xpp.elements.Selection

final class AllFieldsSelection = Impl::AllFieldsSelection;
