// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AndExpression`.
 */

private import internal.AndExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class AndExpression = Impl::AndExpression;
