// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AnyType`.
 */

private import internal.AnyTypeImpl
import codeql.xpp.elements.XppType

final class AnyType = Impl::AnyType;
