// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ArraySpecification`.
 */

private import internal.ArraySpecificationImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.Expression

final class ArraySpecification = Impl::ArraySpecification;
