// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AsClrExpression`.
 */

private import internal.AsClrExpressionImpl
import codeql.xpp.elements.IsAsExpression

final class AsClrExpression = Impl::AsClrExpression;
