// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AsExpression`.
 */

private import internal.AsExpressionImpl
import codeql.xpp.elements.IsAsExpression

final class AsExpression = Impl::AsExpression;
