// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignPreIncrementStatement`.
 */

private import internal.AssignPreIncrementStatementImpl
import codeql.xpp.elements.AssignmentSingleField

final class AssignPreIncrementStatement = Impl::AssignPreIncrementStatement;
