// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignmentEventHandlerInstance`.
 */

private import internal.AssignmentEventHandlerInstanceImpl
import codeql.xpp.elements.AssignmentEventHandlerBase
import codeql.xpp.elements.Qualifier

final class AssignmentEventHandlerInstance = Impl::AssignmentEventHandlerInstance;
