// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignPostIncrementStatement`.
 */

private import internal.AssignPostIncrementStatementImpl
import codeql.xpp.elements.AssignmentSingleField

final class AssignPostIncrementStatement = Impl::AssignPostIncrementStatement;
