// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignmentEventHandlerClr`.
 */

private import internal.AssignmentEventHandlerClrImpl
import codeql.xpp.elements.AssignmentEventHandlerStatic

final class AssignmentEventHandlerClr = Impl::AssignmentEventHandlerClr;
