// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignmentEventHandlerBase`.
 */

private import internal.AssignmentEventHandlerBaseImpl
import codeql.xpp.elements.AssignmentSingleField

final class AssignmentEventHandlerBase = Impl::AssignmentEventHandlerBase;
