// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignDecrementStatement`.
 */

private import internal.AssignDecrementStatementImpl
import codeql.xpp.elements.AssignmentBinary

final class AssignDecrementStatement = Impl::AssignDecrementStatement;
