// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignDivideStatement`.
 */

private import internal.AssignDivideStatementImpl
import codeql.xpp.elements.AssignmentBinary

final class AssignDivideStatement = Impl::AssignDivideStatement;
