// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignEqualStatement`.
 */

private import internal.AssignEqualStatementImpl
import codeql.xpp.elements.AssignmentBinary

final class AssignEqualStatement = Impl::AssignEqualStatement;
