// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignmentStatement`.
 */

private import internal.AssignmentStatementImpl
import codeql.xpp.elements.Statement

final class AssignmentStatement = Impl::AssignmentStatement;
