// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignmentBinary`.
 */

private import internal.AssignmentBinaryImpl
import codeql.xpp.elements.AssignmentSingleField
import codeql.xpp.elements.Expression

final class AssignmentBinary = Impl::AssignmentBinary;
