// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignMultipleFieldStatement`.
 */

private import internal.AssignMultipleFieldStatementImpl
import codeql.xpp.elements.AssignmentStatement
import codeql.xpp.elements.Expression
import codeql.xpp.elements.FieldSpecification

final class AssignMultipleFieldStatement = Impl::AssignMultipleFieldStatement;
