// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignMultiplyStatement`.
 */

private import internal.AssignMultiplyStatementImpl
import codeql.xpp.elements.AssignmentBinary

final class AssignMultiplyStatement = Impl::AssignMultiplyStatement;
