// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignmentEventHandlerStaticInternal`.
 */

private import internal.AssignmentEventHandlerStaticInternalImpl
import codeql.xpp.elements.AssignmentEventHandlerStatic

final class AssignmentEventHandlerStaticInternal = Impl::AssignmentEventHandlerStaticInternal;
