// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignmentSingleField`.
 */

private import internal.AssignmentSingleFieldImpl
import codeql.xpp.elements.AssignmentStatement
import codeql.xpp.elements.FieldSpecification

final class AssignmentSingleField = Impl::AssignmentSingleField;
