// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignPreDecrementStatement`.
 */

private import internal.AssignPreDecrementStatementImpl
import codeql.xpp.elements.AssignmentSingleField

final class AssignPreDecrementStatement = Impl::AssignPreDecrementStatement;
