// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignPostDecrementStatement`.
 */

private import internal.AssignPostDecrementStatementImpl
import codeql.xpp.elements.AssignmentSingleField

final class AssignPostDecrementStatement = Impl::AssignPostDecrementStatement;
