// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignmentEventHandlerStatic`.
 */

private import internal.AssignmentEventHandlerStaticImpl
import codeql.xpp.elements.AssignmentEventHandlerBase

final class AssignmentEventHandlerStatic = Impl::AssignmentEventHandlerStatic;
