// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AssignIncrementStatement`.
 */

private import internal.AssignIncrementStatementImpl
import codeql.xpp.elements.AssignmentBinary

final class AssignIncrementStatement = Impl::AssignIncrementStatement;
