// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Ast`.
 */

private import internal.AstImpl
import codeql.xpp.elements.Locatable

/**
 * Root of the X++ abstract syntax tree.
 *
 * This mirrors `Microsoft.Dynamics.AX.Metadata.XppCompiler.Ast`, the base class of the
 * X++ compiler's own AST.
 */
final class Ast = Impl::Ast;
