// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AttributeExpression`.
 */

private import internal.AttributeExpressionImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.AttributeLiteral

final class AttributeExpression = Impl::AttributeExpression;
