// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Attribute`.
 */

private import internal.AttributeImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.AttributeExpression
import codeql.xpp.elements.AttributeNamedParameterEntry

final class Attribute = Impl::Attribute;
