// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AttributeList`.
 */

private import internal.AttributeListImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.Attribute

final class AttributeList = Impl::AttributeList;
