// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AttributeLiteral`.
 */

private import internal.AttributeLiteralImpl
import codeql.xpp.elements.Ast

final class AttributeLiteral = Impl::AttributeLiteral;
