// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AttributeNamedParameterEntry`.
 */

private import internal.AttributeNamedParameterEntryImpl
import codeql.xpp.elements.AttributeExpression
import codeql.xpp.elements.XppTuple

final class AttributeNamedParameterEntry = Impl::AttributeNamedParameterEntry;
