// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `AvgAggregateSelection`.
 */

private import internal.AvgAggregateSelectionImpl
import codeql.xpp.elements.AggregateSelection

final class AvgAggregateSelection = Impl::AvgAggregateSelection;
