// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `BinaryExpression`.
 */

private import internal.BinaryExpressionImpl
import codeql.xpp.elements.Expression

final class BinaryExpression = Impl::BinaryExpression;
