// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `BooleanType`.
 */

private import internal.BooleanTypeImpl
import codeql.xpp.elements.XppType

final class BooleanType = Impl::BooleanType;
