// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `BooleanLiteralExpression`.
 */

private import internal.BooleanLiteralExpressionImpl
import codeql.xpp.elements.DefaultTypeLiteralExpression

final class BooleanLiteralExpression = Impl::BooleanLiteralExpression;
