// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `BooleanAttributeLiteral`.
 */

private import internal.BooleanAttributeLiteralImpl
import codeql.xpp.elements.DefaultTypeAttributeLiteral

final class BooleanAttributeLiteral = Impl::BooleanAttributeLiteral;
