// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `BreakStatement`.
 */

private import internal.BreakStatementImpl
import codeql.xpp.elements.Statement

final class BreakStatement = Impl::BreakStatement;
