// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `BreakpointStatement`.
 */

private import internal.BreakpointStatementImpl
import codeql.xpp.elements.Statement

final class BreakpointStatement = Impl::BreakpointStatement;
