// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Case`.
 */

private import internal.CaseImpl
import codeql.xpp.elements.Ast

final class Case = Impl::Case;
