// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `CaseDefault`.
 */

private import internal.CaseDefaultImpl
import codeql.xpp.elements.Case

final class CaseDefault = Impl::CaseDefault;
