// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `CaseValues`.
 */

private import internal.CaseValuesImpl
import codeql.xpp.elements.Case
import codeql.xpp.elements.Expression

final class CaseValues = Impl::CaseValues;
