// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `CatchExpression`.
 */

private import internal.CatchExpressionImpl
import codeql.xpp.elements.Catch
import codeql.xpp.elements.Expression

final class CatchExpression = Impl::CatchExpression;
