// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `CatchUpdateConflict`.
 */

private import internal.CatchUpdateConflictImpl
import codeql.xpp.elements.Catch
import codeql.xpp.elements.Expression
import codeql.xpp.elements.InstanceName

final class CatchUpdateConflict = Impl::CatchUpdateConflict;
