// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `CatchAllValues`.
 */

private import internal.CatchAllValuesImpl
import codeql.xpp.elements.Catch

final class CatchAllValues = Impl::CatchAllValues;
