// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Catch`.
 */

private import internal.CatchImpl
import codeql.xpp.elements.Ast

final class Catch = Impl::Catch;
