// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ChangeStatement`.
 */

private import internal.ChangeStatementImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Statement

final class ChangeStatement = Impl::ChangeStatement;
