// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ChangeCompanyStatement`.
 */

private import internal.ChangeCompanyStatementImpl
import codeql.xpp.elements.ChangeStatement

final class ChangeCompanyStatement = Impl::ChangeCompanyStatement;
