// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ClassOrInterface`.
 */

private import internal.ClassOrInterfaceImpl
import codeql.xpp.elements.AttributeList
import codeql.xpp.elements.ModelElement

final class ClassOrInterface = Impl::ClassOrInterface;
