// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Class`.
 */

private import internal.ClassImpl
import codeql.xpp.elements.ClassOrInterface
import codeql.xpp.elements.FieldDeclaration

final class Class = Impl::Class;
