// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ClassAccessModifier`.
 */

private import internal.ClassAccessModifierImpl
import codeql.xpp.elements.Ast

final class ClassAccessModifier = Impl::ClassAccessModifier;
