// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ClrEnumerationLiteralExpression`.
 */

private import internal.ClrEnumerationLiteralExpressionImpl
import codeql.xpp.elements.LiteralExpression

final class ClrEnumerationLiteralExpression = Impl::ClrEnumerationLiteralExpression;
