// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ClrType`.
 */

private import internal.ClrTypeImpl
import codeql.xpp.elements.GenericXppType

final class ClrType = Impl::ClrType;
