// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Comment`.
 */

private import internal.CommentImpl
import codeql.xpp.elements.Locatable

/**
 * A comment in X++ source.
 */
final class Comment = Impl::Comment;
