// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `CompilationUnitRegionEntry`.
 */

private import internal.CompilationUnitRegionEntryImpl
import codeql.xpp.elements.Comment
import codeql.xpp.elements.XppTuple

final class CompilationUnitRegionEntry = Impl::CompilationUnitRegionEntry;
