// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `CompoundStatement`.
 */

private import internal.CompoundStatementImpl
import codeql.xpp.elements.Statement

final class CompoundStatement = Impl::CompoundStatement;
