// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `CompilationUnit`.
 */

private import internal.CompilationUnitImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.Comment
import codeql.xpp.elements.CompilationUnitRegionEntry

final class CompilationUnit = Impl::CompilationUnit;
