// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ConditionalExpression`.
 */

private import internal.ConditionalExpressionImpl
import codeql.xpp.elements.Expression

final class ConditionalExpression = Impl::ConditionalExpression;
