// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ContinueStatement`.
 */

private import internal.ContinueStatementImpl
import codeql.xpp.elements.Statement

final class ContinueStatement = Impl::ContinueStatement;
