// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ContainerAttributeLiteral`.
 */

private import internal.ContainerAttributeLiteralImpl
import codeql.xpp.elements.AttributeExpression
import codeql.xpp.elements.AttributeLiteral

final class ContainerAttributeLiteral = Impl::ContainerAttributeLiteral;
