// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ContainerLiteralExpression`.
 */

private import internal.ContainerLiteralExpressionImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.LiteralExpression

final class ContainerLiteralExpression = Impl::ContainerLiteralExpression;
