// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ContainerType`.
 */

private import internal.ContainerTypeImpl
import codeql.xpp.elements.XppType

final class ContainerType = Impl::ContainerType;
