// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `CountAggregateSelection`.
 */

private import internal.CountAggregateSelectionImpl
import codeql.xpp.elements.AggregateSelection

final class CountAggregateSelection = Impl::CountAggregateSelection;
