// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `CrossCompanyContainer`.
 */

private import internal.CrossCompanyContainerImpl
import codeql.xpp.elements.CrossCompany
import codeql.xpp.elements.Expression

final class CrossCompanyContainer = Impl::CrossCompanyContainer;
