// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `CrossCompanyAll`.
 */

private import internal.CrossCompanyAllImpl
import codeql.xpp.elements.CrossCompany

final class CrossCompanyAll = Impl::CrossCompanyAll;
