// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `CrossCompany`.
 */

private import internal.CrossCompanyImpl
import codeql.xpp.elements.Ast

final class CrossCompany = Impl::CrossCompany;
