// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DateType`.
 */

private import internal.DateTypeImpl
import codeql.xpp.elements.XppType

final class DateType = Impl::DateType;
