// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DateTimeAttributeLiteral`.
 */

private import internal.DateTimeAttributeLiteralImpl
import codeql.xpp.elements.DefaultTypeAttributeLiteral

final class DateTimeAttributeLiteral = Impl::DateTimeAttributeLiteral;
