// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DateLiteralExpression`.
 */

private import internal.DateLiteralExpressionImpl
import codeql.xpp.elements.DefaultTypeLiteralExpression

final class DateLiteralExpression = Impl::DateLiteralExpression;
