// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DateTimeLiteralExpression`.
 */

private import internal.DateTimeLiteralExpressionImpl
import codeql.xpp.elements.DefaultTypeLiteralExpression

final class DateTimeLiteralExpression = Impl::DateTimeLiteralExpression;
