// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DateTimeType`.
 */

private import internal.DateTimeTypeImpl
import codeql.xpp.elements.XppType

final class DateTimeType = Impl::DateTimeType;
