// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DateAttributeLiteral`.
 */

private import internal.DateAttributeLiteralImpl
import codeql.xpp.elements.DefaultTypeAttributeLiteral

final class DateAttributeLiteral = Impl::DateAttributeLiteral;
