// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DblAttributeLiteral`.
 */

private import internal.DblAttributeLiteralImpl
import codeql.xpp.elements.DefaultTypeAttributeLiteral

final class DblAttributeLiteral = Impl::DblAttributeLiteral;
