// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DblType`.
 */

private import internal.DblTypeImpl
import codeql.xpp.elements.XppType

final class DblType = Impl::DblType;
