// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Declaration`.
 */

private import internal.DeclarationImpl
import codeql.xpp.elements.ArraySpecification
import codeql.xpp.elements.CompilationUnit
import codeql.xpp.elements.Modifier
import codeql.xpp.elements.XppType

final class Declaration = Impl::Declaration;
