// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DefaultTypeAttributeLiteral`.
 */

private import internal.DefaultTypeAttributeLiteralImpl
import codeql.xpp.elements.AttributeLiteral

final class DefaultTypeAttributeLiteral = Impl::DefaultTypeAttributeLiteral;
