// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DefaultTypeLiteralExpression`.
 */

private import internal.DefaultTypeLiteralExpressionImpl
import codeql.xpp.elements.LiteralExpression

final class DefaultTypeLiteralExpression = Impl::DefaultTypeLiteralExpression;
