// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DeleteStatement`.
 */

private import internal.DeleteStatementImpl
import codeql.xpp.elements.Query
import codeql.xpp.elements.Statement

final class DeleteStatement = Impl::DeleteStatement;
