// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Delegate`.
 */

private import internal.DelegateImpl
import codeql.xpp.elements.MethodOrDelegate

final class Delegate = Impl::Delegate;
