// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DivideExpression`.
 */

private import internal.DivideExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class DivideExpression = Impl::DivideExpression;
