// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `DoWhileStatement`.
 */

private import internal.DoWhileStatementImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Statement

final class DoWhileStatement = Impl::DoWhileStatement;
