// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `EmptyExpression`.
 */

private import internal.EmptyExpressionImpl
import codeql.xpp.elements.Expression

final class EmptyExpression = Impl::EmptyExpression;
