// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `EmptyStatement`.
 */

private import internal.EmptyStatementImpl
import codeql.xpp.elements.Statement

final class EmptyStatement = Impl::EmptyStatement;
