// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `EnumerationLiteralExpression`.
 */

private import internal.EnumerationLiteralExpressionImpl
import codeql.xpp.elements.LiteralExpression

final class EnumerationLiteralExpression = Impl::EnumerationLiteralExpression;
