// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `EnumAttributeLiteral`.
 */

private import internal.EnumAttributeLiteralImpl
import codeql.xpp.elements.AttributeLiteral

final class EnumAttributeLiteral = Impl::EnumAttributeLiteral;
