// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `EnumerationType`.
 */

private import internal.EnumerationTypeImpl
import codeql.xpp.elements.XppType

final class EnumerationType = Impl::EnumerationType;
