// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `EqualExpression`.
 */

private import internal.EqualExpressionImpl
import codeql.xpp.elements.RelationalExpression

final class EqualExpression = Impl::EqualExpression;
