// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ErrorElement`.
 */

private import internal.ErrorElementImpl
import codeql.xpp.elements.Locatable

/**
 * The superclass of all elements indicating some kind of error.
 */
final class ErrorElement = Impl::ErrorElement;
