// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `EvaluationActualParameterEntry`.
 */

private import internal.EvaluationActualParameterEntryImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.XppTuple

final class EvaluationActualParameterEntry = Impl::EvaluationActualParameterEntry;
