// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ExplicitSelection`.
 */

private import internal.ExplicitSelectionImpl
import codeql.xpp.elements.Selection
import codeql.xpp.elements.SelectionField

final class ExplicitSelection = Impl::ExplicitSelection;
