// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ExpressionStatement`.
 */

private import internal.ExpressionStatementImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Statement

final class ExpressionStatement = Impl::ExpressionStatement;
