// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ExpressionCompilationUnit`.
 */

private import internal.ExpressionCompilationUnitImpl
import codeql.xpp.elements.CompilationUnit
import codeql.xpp.elements.Expression

final class ExpressionCompilationUnit = Impl::ExpressionCompilationUnit;
