// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Expression`.
 */

private import internal.ExpressionImpl
import codeql.xpp.elements.Ast

final class Expression = Impl::Expression;
