// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ExpressionQualifier`.
 */

private import internal.ExpressionQualifierImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Qualifier

final class ExpressionQualifier = Impl::ExpressionQualifier;
