// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FieldDeclarationInternal`.
 */

private import internal.FieldDeclarationInternalImpl
import codeql.xpp.elements.FieldDeclaration

final class FieldDeclarationInternal = Impl::FieldDeclarationInternal;
