// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FieldExpressionInternal`.
 */

private import internal.FieldExpressionInternalImpl
import codeql.xpp.elements.FieldExpression

final class FieldExpressionInternal = Impl::FieldExpressionInternal;
