// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FieldAssignment`.
 */

private import internal.FieldAssignmentImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.Expression

final class FieldAssignment = Impl::FieldAssignment;
