// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FieldSelection`.
 */

private import internal.FieldSelectionImpl
import codeql.xpp.elements.SelectionField

final class FieldSelection = Impl::FieldSelection;
