// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FieldDeclaration`.
 */

private import internal.FieldDeclarationImpl
import codeql.xpp.elements.AttributeList
import codeql.xpp.elements.Declaration
import codeql.xpp.elements.Expression

final class FieldDeclaration = Impl::FieldDeclaration;
