// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FieldExpression`.
 */

private import internal.FieldExpressionImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.FieldSpecification

final class FieldExpression = Impl::FieldExpression;
