// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FieldSpecification`.
 */

private import internal.FieldSpecificationImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Qualifier

final class FieldSpecification = Impl::FieldSpecification;
