// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `File`.
 */

private import internal.FileImpl
import codeql.xpp.elements.Element

final class File = Impl::File;
