// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FindStatement`.
 */

private import internal.FindStatementImpl
import codeql.xpp.elements.Query
import codeql.xpp.elements.Statement

final class FindStatement = Impl::FindStatement;
