// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FlushStatement`.
 */

private import internal.FlushStatementImpl
import codeql.xpp.elements.Statement

final class FlushStatement = Impl::FlushStatement;
