// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ForAssign`.
 */

private import internal.ForAssignImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.FieldSpecification

final class ForAssign = Impl::ForAssign;
