// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ForDeclarationAssign`.
 */

private import internal.ForDeclarationAssignImpl
import codeql.xpp.elements.ForAssign
import codeql.xpp.elements.VariableDeclaration

final class ForDeclarationAssign = Impl::ForDeclarationAssign;
