// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ForExpressionAssign`.
 */

private import internal.ForExpressionAssignImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.ForAssign

final class ForExpressionAssign = Impl::ForExpressionAssign;
