// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ForFieldIncrementAssign`.
 */

private import internal.ForFieldIncrementAssignImpl
import codeql.xpp.elements.ForExpressionAssign

final class ForFieldIncrementAssign = Impl::ForFieldIncrementAssign;
