// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ForFieldDecrementAssign`.
 */

private import internal.ForFieldDecrementAssignImpl
import codeql.xpp.elements.ForExpressionAssign

final class ForFieldDecrementAssign = Impl::ForFieldDecrementAssign;
