// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ForFieldPostIncrement`.
 */

private import internal.ForFieldPostIncrementImpl
import codeql.xpp.elements.ForAssign

final class ForFieldPostIncrement = Impl::ForFieldPostIncrement;
