// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ForFieldPreDecrement`.
 */

private import internal.ForFieldPreDecrementImpl
import codeql.xpp.elements.ForAssign

final class ForFieldPreDecrement = Impl::ForFieldPreDecrement;
