// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ForFieldPreIncrement`.
 */

private import internal.ForFieldPreIncrementImpl
import codeql.xpp.elements.ForAssign

final class ForFieldPreIncrement = Impl::ForFieldPreIncrement;
