// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ForFieldPostDecrement`.
 */

private import internal.ForFieldPostDecrementImpl
import codeql.xpp.elements.ForAssign

final class ForFieldPostDecrement = Impl::ForFieldPostDecrement;
