// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ForFieldAssign`.
 */

private import internal.ForFieldAssignImpl
import codeql.xpp.elements.ForExpressionAssign

final class ForFieldAssign = Impl::ForFieldAssign;
