// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FormControl`.
 */

private import internal.FormControlImpl
import codeql.xpp.elements.FormNestedElement

final class FormControl = Impl::FormControl;
