// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FormElementType`.
 */

private import internal.FormElementTypeImpl
import codeql.xpp.elements.NamedType

final class FormElementType = Impl::FormElementType;
