// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FormNestedElement`.
 */

private import internal.FormNestedElementImpl
import codeql.xpp.elements.FormModelElement
import codeql.xpp.elements.ModelElement

final class FormNestedElement = Impl::FormNestedElement;
