// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FormDataField`.
 */

private import internal.FormDataFieldImpl
import codeql.xpp.elements.FormDataSource
import codeql.xpp.elements.FormNestedElement

final class FormDataField = Impl::FormDataField;
