// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FormModelElement`.
 */

private import internal.FormModelElementImpl
import codeql.xpp.elements.Class
import codeql.xpp.elements.FormControl
import codeql.xpp.elements.FormDataSource
import codeql.xpp.elements.ModelElement

final class FormModelElement = Impl::FormModelElement;
