// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FormDataSource`.
 */

private import internal.FormDataSourceImpl
import codeql.xpp.elements.FormDataField
import codeql.xpp.elements.FormNestedElement
import codeql.xpp.elements.QueryModelElement

final class FormDataSource = Impl::FormDataSource;
