// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ForStatement`.
 */

private import internal.ForStatementImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.ForAssign
import codeql.xpp.elements.Statement

final class ForStatement = Impl::ForStatement;
