// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FunctionCall`.
 */

private import internal.FunctionCallImpl
import codeql.xpp.elements.GenericEvaluation

final class FunctionCall = Impl::FunctionCall;
