// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `FunctionDeclaration`.
 */

private import internal.FunctionDeclarationImpl
import codeql.xpp.elements.LocalDeclaration
import codeql.xpp.elements.ParameterDeclaration
import codeql.xpp.elements.Statement

final class FunctionDeclaration = Impl::FunctionDeclaration;
