// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `GenericEvaluation`.
 */

private import internal.GenericEvaluationImpl
import codeql.xpp.elements.Evaluation
import codeql.xpp.elements.XppType

final class GenericEvaluation = Impl::GenericEvaluation;
