// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `GenericXppType`.
 */

private import internal.GenericXppTypeImpl
import codeql.xpp.elements.XppType

final class GenericXppType = Impl::GenericXppType;
