// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `GlobalOrderElement`.
 */

private import internal.GlobalOrderElementImpl
import codeql.xpp.elements.OrderElement

final class GlobalOrderElement = Impl::GlobalOrderElement;
