// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `GreaterThanOrEqualExpression`.
 */

private import internal.GreaterThanOrEqualExpressionImpl
import codeql.xpp.elements.RelationalExpression

final class GreaterThanOrEqualExpression = Impl::GreaterThanOrEqualExpression;
