// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `GreaterThanExpression`.
 */

private import internal.GreaterThanExpressionImpl
import codeql.xpp.elements.RelationalExpression

final class GreaterThanExpression = Impl::GreaterThanExpression;
