// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `GuidType`.
 */

private import internal.GuidTypeImpl
import codeql.xpp.elements.XppType

final class GuidType = Impl::GuidType;
