// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `GuidAttributeLiteral`.
 */

private import internal.GuidAttributeLiteralImpl
import codeql.xpp.elements.DefaultTypeAttributeLiteral

final class GuidAttributeLiteral = Impl::GuidAttributeLiteral;
