// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `IfStatement`.
 */

private import internal.IfStatementImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Statement

final class IfStatement = Impl::IfStatement;
