// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `IfThenElseStatement`.
 */

private import internal.IfThenElseStatementImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Statement

final class IfThenElseStatement = Impl::IfThenElseStatement;
