// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ImplicitSelection`.
 */

private import internal.ImplicitSelectionImpl
import codeql.xpp.elements.Selection

final class ImplicitSelection = Impl::ImplicitSelection;
