// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `InExpression`.
 */

private import internal.InExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class InExpression = Impl::InExpression;
