// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `InsertStatement`.
 */

private import internal.InsertStatementImpl
import codeql.xpp.elements.CrossCompany
import codeql.xpp.elements.InsertFieldSpecification
import codeql.xpp.elements.Query
import codeql.xpp.elements.Statement

final class InsertStatement = Impl::InsertStatement;
