// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `InsertFieldSpecification`.
 */

private import internal.InsertFieldSpecificationImpl
import codeql.xpp.elements.Ast

final class InsertFieldSpecification = Impl::InsertFieldSpecification;
