// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `InstanceName`.
 */

private import internal.InstanceNameImpl
import codeql.xpp.elements.Ast

final class InstanceName = Impl::InstanceName;
