// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Int64LiteralExpression`.
 */

private import internal.Int64LiteralExpressionImpl
import codeql.xpp.elements.DefaultTypeLiteralExpression

final class Int64LiteralExpression = Impl::Int64LiteralExpression;
