// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Int64AttributeLiteral`.
 */

private import internal.Int64AttributeLiteralImpl
import codeql.xpp.elements.DefaultTypeAttributeLiteral

final class Int64AttributeLiteral = Impl::Int64AttributeLiteral;
