// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Int64Type`.
 */

private import internal.Int64TypeImpl
import codeql.xpp.elements.XppType

final class Int64Type = Impl::Int64Type;
