// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `IntAttributeLiteral`.
 */

private import internal.IntAttributeLiteralImpl
import codeql.xpp.elements.DefaultTypeAttributeLiteral

final class IntAttributeLiteral = Impl::IntAttributeLiteral;
