// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `IntegerDivideExpression`.
 */

private import internal.IntegerDivideExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class IntegerDivideExpression = Impl::IntegerDivideExpression;
