// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Interface`.
 */

private import internal.InterfaceImpl
import codeql.xpp.elements.ClassOrInterface

final class Interface = Impl::Interface;
