// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `IntLiteralExpression`.
 */

private import internal.IntLiteralExpressionImpl
import codeql.xpp.elements.DefaultTypeLiteralExpression

final class IntLiteralExpression = Impl::IntLiteralExpression;
