// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Intrinsic`.
 */

private import internal.IntrinsicImpl
import codeql.xpp.elements.Expression

final class Intrinsic = Impl::Intrinsic;
