// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `IntrinsicAttributeLiteral`.
 */

private import internal.IntrinsicAttributeLiteralImpl
import codeql.xpp.elements.AttributeLiteral

final class IntrinsicAttributeLiteral = Impl::IntrinsicAttributeLiteral;
