// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `IntType`.
 */

private import internal.IntTypeImpl
import codeql.xpp.elements.XppType

final class IntType = Impl::IntType;
