// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `IsAsExpression`.
 */

private import internal.IsAsExpressionImpl
import codeql.xpp.elements.Expression

final class IsAsExpression = Impl::IsAsExpression;
