// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `IsClrExpression`.
 */

private import internal.IsClrExpressionImpl
import codeql.xpp.elements.IsAsExpression

final class IsClrExpression = Impl::IsClrExpression;
