// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `IsExpression`.
 */

private import internal.IsExpressionImpl
import codeql.xpp.elements.IsAsExpression

final class IsExpression = Impl::IsExpression;
