// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `JoinSpecification`.
 */

private import internal.JoinSpecificationImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.Query

final class JoinSpecification = Impl::JoinSpecification;
