// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `LessThanOrEqualExpression`.
 */

private import internal.LessThanOrEqualExpressionImpl
import codeql.xpp.elements.RelationalExpression

final class LessThanOrEqualExpression = Impl::LessThanOrEqualExpression;
