// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `LessThanExpression`.
 */

private import internal.LessThanExpressionImpl
import codeql.xpp.elements.RelationalExpression

final class LessThanExpression = Impl::LessThanExpression;
