// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `LikeExpression`.
 */

private import internal.LikeExpressionImpl
import codeql.xpp.elements.RelationalExpression

final class LikeExpression = Impl::LikeExpression;
