// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `LiteralExpression`.
 */

private import internal.LiteralExpressionImpl
import codeql.xpp.elements.Expression

final class LiteralExpression = Impl::LiteralExpression;
