// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Locatable`.
 */

private import internal.LocatableImpl
import codeql.xpp.elements.Element
import codeql.xpp.elements.Location

final class Locatable = Impl::Locatable;
