// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `LocalDeclarationsStatement`.
 */

private import internal.LocalDeclarationsStatementImpl
import codeql.xpp.elements.LocalDeclaration
import codeql.xpp.elements.Statement

final class LocalDeclarationsStatement = Impl::LocalDeclarationsStatement;
