// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `LocalDeclaration`.
 */

private import internal.LocalDeclarationImpl
import codeql.xpp.elements.Declaration

final class LocalDeclaration = Impl::LocalDeclaration;
