// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Location`.
 */

private import internal.LocationImpl
import codeql.xpp.elements.Element
import codeql.xpp.elements.File

final class Location = Impl::Location;
