// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `MaxAggregateSelection`.
 */

private import internal.MaxAggregateSelectionImpl
import codeql.xpp.elements.AggregateSelection

final class MaxAggregateSelection = Impl::MaxAggregateSelection;
