// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Method`.
 */

private import internal.MethodImpl
import codeql.xpp.elements.LocalDeclaration
import codeql.xpp.elements.MethodOrDelegate
import codeql.xpp.elements.Statement

final class Method = Impl::Method;
