// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `MethodOrDelegate`.
 */

private import internal.MethodOrDelegateImpl
import codeql.xpp.elements.AttributeList
import codeql.xpp.elements.CompilationUnit
import codeql.xpp.elements.Modifier
import codeql.xpp.elements.ParameterDeclaration
import codeql.xpp.elements.XppType

final class MethodOrDelegate = Impl::MethodOrDelegate;
