// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `MinAggregateSelection`.
 */

private import internal.MinAggregateSelectionImpl
import codeql.xpp.elements.AggregateSelection

final class MinAggregateSelection = Impl::MinAggregateSelection;
