// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ModExpression`.
 */

private import internal.ModExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class ModExpression = Impl::ModExpression;
