// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ModelElement`.
 */

private import internal.ModelElementImpl
import codeql.xpp.elements.ClassAccessModifier
import codeql.xpp.elements.ClassOrInterface
import codeql.xpp.elements.CompilationUnit
import codeql.xpp.elements.MethodOrDelegate
import codeql.xpp.elements.ModelElementUsingEntry
import codeql.xpp.elements.XppType

final class ModelElement = Impl::ModelElement;
