// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ModelElementUsingEntry`.
 */

private import internal.ModelElementUsingEntryImpl
import codeql.xpp.elements.XppTuple

final class ModelElementUsingEntry = Impl::ModelElementUsingEntry;
