// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Modifier`.
 */

private import internal.ModifierImpl
import codeql.xpp.elements.Ast

final class Modifier = Impl::Modifier;
