// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `MoveCursorStatement`.
 */

private import internal.MoveCursorStatementImpl
import codeql.xpp.elements.Selection
import codeql.xpp.elements.Statement

final class MoveCursorStatement = Impl::MoveCursorStatement;
