// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `MultiplyExpression`.
 */

private import internal.MultiplyExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class MultiplyExpression = Impl::MultiplyExpression;
