// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `NamedType`.
 */

private import internal.NamedTypeImpl
import codeql.xpp.elements.GenericXppType

final class NamedType = Impl::NamedType;
