// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `NamedTypeInternal`.
 */

private import internal.NamedTypeInternalImpl
import codeql.xpp.elements.NamedType

final class NamedTypeInternal = Impl::NamedTypeInternal;
