// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `NamedFieldReference`.
 */

private import internal.NamedFieldReferenceImpl
import codeql.xpp.elements.TableFieldReference

final class NamedFieldReference = Impl::NamedFieldReference;
