// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `NewClrCall`.
 */

private import internal.NewClrCallImpl
import codeql.xpp.elements.GenericEvaluation

final class NewClrCall = Impl::NewClrCall;
