// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `NewClrArrayExpression`.
 */

private import internal.NewClrArrayExpressionImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.XppType

final class NewClrArrayExpression = Impl::NewClrArrayExpression;
