// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `NewCall`.
 */

private import internal.NewCallImpl
import codeql.xpp.elements.Evaluation
import codeql.xpp.elements.XppType

final class NewCall = Impl::NewCall;
