// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `NextExpression`.
 */

private import internal.NextExpressionImpl
import codeql.xpp.elements.Evaluation

final class NextExpression = Impl::NextExpression;
