// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `NotEqualExpression`.
 */

private import internal.NotEqualExpressionImpl
import codeql.xpp.elements.RelationalExpression

final class NotEqualExpression = Impl::NotEqualExpression;
