// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `NotExpression`.
 */

private import internal.NotExpressionImpl
import codeql.xpp.elements.UnaryExpression

final class NotExpression = Impl::NotExpression;
