// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `NullLiteralExpression`.
 */

private import internal.NullLiteralExpressionImpl
import codeql.xpp.elements.LiteralExpression

final class NullLiteralExpression = Impl::NullLiteralExpression;
