// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `NumberedFieldReference`.
 */

private import internal.NumberedFieldReferenceImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.TableFieldReference

final class NumberedFieldReference = Impl::NumberedFieldReference;
