// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `OrderElement`.
 */

private import internal.OrderElementImpl
import codeql.xpp.elements.Ast

final class OrderElement = Impl::OrderElement;
