// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `OrExpression`.
 */

private import internal.OrExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class OrExpression = Impl::OrExpression;
