// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ParameterDeclaration`.
 */

private import internal.ParameterDeclarationImpl
import codeql.xpp.elements.VariableDeclaration

final class ParameterDeclaration = Impl::ParameterDeclaration;
