// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `PhysicalNotExpression`.
 */

private import internal.PhysicalNotExpressionImpl
import codeql.xpp.elements.UnaryExpression

final class PhysicalNotExpression = Impl::PhysicalNotExpression;
