// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `PhysicalXorExpression`.
 */

private import internal.PhysicalXorExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class PhysicalXorExpression = Impl::PhysicalXorExpression;
