// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `PhysicalOrExpression`.
 */

private import internal.PhysicalOrExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class PhysicalOrExpression = Impl::PhysicalOrExpression;
