// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `PhysicalAndExpression`.
 */

private import internal.PhysicalAndExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class PhysicalAndExpression = Impl::PhysicalAndExpression;
