// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Placeholder`.
 */

private import internal.PlaceholderImpl
import codeql.xpp.elements.Expression

final class Placeholder = Impl::Placeholder;
