// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `PrintStatement`.
 */

private import internal.PrintStatementImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Statement

final class PrintStatement = Impl::PrintStatement;
