// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ProvidedTypeStaticCall`.
 */

private import internal.ProvidedTypeStaticCallImpl
import codeql.xpp.elements.Evaluation
import codeql.xpp.elements.ProvidedType

final class ProvidedTypeStaticCall = Impl::ProvidedTypeStaticCall;
