// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ProvidedType`.
 */

private import internal.ProvidedTypeImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.XppType

final class ProvidedType = Impl::ProvidedType;
