// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `QualifiedStaticFieldExpression`.
 */

private import internal.QualifiedStaticFieldExpressionImpl
import codeql.xpp.elements.FieldExpression

final class QualifiedStaticFieldExpression = Impl::QualifiedStaticFieldExpression;
