// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `QualifiedStaticField`.
 */

private import internal.QualifiedStaticFieldImpl
import codeql.xpp.elements.FieldSpecification

final class QualifiedStaticField = Impl::QualifiedStaticField;
