// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `QualifiedField`.
 */

private import internal.QualifiedFieldImpl
import codeql.xpp.elements.FieldSpecification

final class QualifiedField = Impl::QualifiedField;
