// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `QualifiedStaticCall`.
 */

private import internal.QualifiedStaticCallImpl
import codeql.xpp.elements.GenericEvaluation
import codeql.xpp.elements.Qualifier
import codeql.xpp.elements.XppType

final class QualifiedStaticCall = Impl::QualifiedStaticCall;
