// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Qualifier`.
 */

private import internal.QualifierImpl
import codeql.xpp.elements.Ast

final class Qualifier = Impl::Qualifier;
