// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `QualifiedNumberedField`.
 */

private import internal.QualifiedNumberedFieldImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.FieldSpecification

final class QualifiedNumberedField = Impl::QualifiedNumberedField;
