// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `QualifiedCall`.
 */

private import internal.QualifiedCallImpl
import codeql.xpp.elements.GenericEvaluation
import codeql.xpp.elements.Qualifier

final class QualifiedCall = Impl::QualifiedCall;
