// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `QualifiedInstanceName`.
 */

private import internal.QualifiedInstanceNameImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.InstanceName
import codeql.xpp.elements.Qualifier

final class QualifiedInstanceName = Impl::QualifiedInstanceName;
