// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `QueryDataSourceRelation`.
 */

private import internal.QueryDataSourceRelationImpl
import codeql.xpp.elements.Ast

final class QueryDataSourceRelation = Impl::QueryDataSourceRelation;
