// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Query`.
 */

private import internal.QueryImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.CrossCompany
import codeql.xpp.elements.Expression
import codeql.xpp.elements.JoinSpecification
import codeql.xpp.elements.OrderElement
import codeql.xpp.elements.Selection
import codeql.xpp.elements.ValidTimeState

final class Query = Impl::Query;
