// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `QueryDataSource`.
 */

private import internal.QueryDataSourceImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.GlobalOrderElement
import codeql.xpp.elements.QueryDataSourceHaving
import codeql.xpp.elements.QueryDataSourceRange
import codeql.xpp.elements.QueryDataSourceRelation

final class QueryDataSource = Impl::QueryDataSource;
