// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `QueryDataSourceHaving`.
 */

private import internal.QueryDataSourceHavingImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.SelectionField

final class QueryDataSourceHaving = Impl::QueryDataSourceHaving;
