// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `QueryDataSourceRange`.
 */

private import internal.QueryDataSourceRangeImpl
import codeql.xpp.elements.Ast

final class QueryDataSourceRange = Impl::QueryDataSourceRange;
