// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `QueryModelElement`.
 */

private import internal.QueryModelElementImpl
import codeql.xpp.elements.Class
import codeql.xpp.elements.ModelElement
import codeql.xpp.elements.QueryDataSource

final class QueryModelElement = Impl::QueryModelElement;
