// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `RealLiteralExpression`.
 */

private import internal.RealLiteralExpressionImpl
import codeql.xpp.elements.DefaultTypeLiteralExpression

final class RealLiteralExpression = Impl::RealLiteralExpression;
