// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `RelationalExpression`.
 */

private import internal.RelationalExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class RelationalExpression = Impl::RelationalExpression;
