// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `RetryStatement`.
 */

private import internal.RetryStatementImpl
import codeql.xpp.elements.Statement

final class RetryStatement = Impl::RetryStatement;
