// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ReturnStatement`.
 */

private import internal.ReturnStatementImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Statement

final class ReturnStatement = Impl::ReturnStatement;
