// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SearchStatement`.
 */

private import internal.SearchStatementImpl
import codeql.xpp.elements.Query
import codeql.xpp.elements.Statement

final class SearchStatement = Impl::SearchStatement;
