// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Selection`.
 */

private import internal.SelectionImpl
import codeql.xpp.elements.Ast

final class Selection = Impl::Selection;
