// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SelectionField`.
 */

private import internal.SelectionFieldImpl
import codeql.xpp.elements.Ast

final class SelectionField = Impl::SelectionField;
