// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ShiftLeftExpression`.
 */

private import internal.ShiftLeftExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class ShiftLeftExpression = Impl::ShiftLeftExpression;
