// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ShiftRightExpression`.
 */

private import internal.ShiftRightExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class ShiftRightExpression = Impl::ShiftRightExpression;
