// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SimpleQualifierInternal`.
 */

private import internal.SimpleQualifierInternalImpl
import codeql.xpp.elements.SimpleQualifier

final class SimpleQualifierInternal = Impl::SimpleQualifierInternal;
