// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SimpleQualifier`.
 */

private import internal.SimpleQualifierImpl
import codeql.xpp.elements.Qualifier

final class SimpleQualifier = Impl::SimpleQualifier;
