// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SimpleField`.
 */

private import internal.SimpleFieldImpl
import codeql.xpp.elements.FieldSpecification

final class SimpleField = Impl::SimpleField;
