// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SimpleInstanceName`.
 */

private import internal.SimpleInstanceNameImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.InstanceName

final class SimpleInstanceName = Impl::SimpleInstanceName;
