// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SimpleOrderElement`.
 */

private import internal.SimpleOrderElementImpl
import codeql.xpp.elements.OrderElement

final class SimpleOrderElement = Impl::SimpleOrderElement;
