// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Statement`.
 */

private import internal.StatementImpl
import codeql.xpp.elements.Ast

final class Statement = Impl::Statement;
