// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `StaticField`.
 */

private import internal.StaticFieldImpl
import codeql.xpp.elements.FieldSpecification

final class StaticField = Impl::StaticField;
