// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `StaticQualifier`.
 */

private import internal.StaticQualifierImpl
import codeql.xpp.elements.SimpleQualifier
import codeql.xpp.elements.XppType

final class StaticQualifier = Impl::StaticQualifier;
