// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `StaticMethodCall`.
 */

private import internal.StaticMethodCallImpl
import codeql.xpp.elements.GenericEvaluation
import codeql.xpp.elements.XppType

final class StaticMethodCall = Impl::StaticMethodCall;
