// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `StringAttributeLiteral`.
 */

private import internal.StringAttributeLiteralImpl
import codeql.xpp.elements.DefaultTypeAttributeLiteral

final class StringAttributeLiteral = Impl::StringAttributeLiteral;
