// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `StringType`.
 */

private import internal.StringTypeImpl
import codeql.xpp.elements.XppType

final class StringType = Impl::StringType;
