// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `StringLiteralExpression`.
 */

private import internal.StringLiteralExpressionImpl
import codeql.xpp.elements.DefaultTypeLiteralExpression

final class StringLiteralExpression = Impl::StringLiteralExpression;
