// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `StringLengthType`.
 */

private import internal.StringLengthTypeImpl
import codeql.xpp.elements.StringType

final class StringLengthType = Impl::StringLengthType;
