// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `StringTypeInternal`.
 */

private import internal.StringTypeInternalImpl
import codeql.xpp.elements.StringType

final class StringTypeInternal = Impl::StringTypeInternal;
