// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SubtractExpression`.
 */

private import internal.SubtractExpressionImpl
import codeql.xpp.elements.BinaryExpression

final class SubtractExpression = Impl::SubtractExpression;
