// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SumAggregateSelection`.
 */

private import internal.SumAggregateSelectionImpl
import codeql.xpp.elements.AggregateSelection

final class SumAggregateSelection = Impl::SumAggregateSelection;
