// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SuperCall`.
 */

private import internal.SuperCallImpl
import codeql.xpp.elements.Evaluation

final class SuperCall = Impl::SuperCall;
