// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SwitchStatementCaseEntry`.
 */

private import internal.SwitchStatementCaseEntryImpl
import codeql.xpp.elements.Case
import codeql.xpp.elements.Statement
import codeql.xpp.elements.XppTuple

final class SwitchStatementCaseEntry = Impl::SwitchStatementCaseEntry;
