// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SwitchStatement`.
 */

private import internal.SwitchStatementImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Statement
import codeql.xpp.elements.SwitchStatementCaseEntry

final class SwitchStatement = Impl::SwitchStatement;
