// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `SwitchCase`.
 */

private import internal.SwitchCaseImpl
import codeql.xpp.elements.Ast

final class SwitchCase = Impl::SwitchCase;
