// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `TableFieldReference`.
 */

private import internal.TableFieldReferenceImpl
import codeql.xpp.elements.Ast
import codeql.xpp.elements.Expression

final class TableFieldReference = Impl::TableFieldReference;
