// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `TableLookupExpression`.
 */

private import internal.TableLookupExpressionImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Query
import codeql.xpp.elements.TableFieldReference

final class TableLookupExpression = Impl::TableLookupExpression;
