// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `Table`.
 */

private import internal.TableImpl
import codeql.xpp.elements.AttributeList
import codeql.xpp.elements.FieldDeclaration
import codeql.xpp.elements.ModelElement

final class Table = Impl::Table;
