// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `TableFieldDeclaration`.
 */

private import internal.TableFieldDeclarationImpl
import codeql.xpp.elements.FieldDeclaration

final class TableFieldDeclaration = Impl::TableFieldDeclaration;
