// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ThrowStatement`.
 */

private import internal.ThrowStatementImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Statement

final class ThrowStatement = Impl::ThrowStatement;
