// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `TryStatement`.
 */

private import internal.TryStatementImpl
import codeql.xpp.elements.Statement
import codeql.xpp.elements.TryStatementCatchEntry

final class TryStatement = Impl::TryStatement;
