// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `TryStatementCatchEntry`.
 */

private import internal.TryStatementCatchEntryImpl
import codeql.xpp.elements.Catch
import codeql.xpp.elements.Statement
import codeql.xpp.elements.XppTuple

final class TryStatementCatchEntry = Impl::TryStatementCatchEntry;
