// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `TtsAbortStatement`.
 */

private import internal.TtsAbortStatementImpl
import codeql.xpp.elements.TtsStatement

final class TtsAbortStatement = Impl::TtsAbortStatement;
