// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `TtsBeginStatement`.
 */

private import internal.TtsBeginStatementImpl
import codeql.xpp.elements.TtsStatement

final class TtsBeginStatement = Impl::TtsBeginStatement;
