// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `TtsEndStatement`.
 */

private import internal.TtsEndStatementImpl
import codeql.xpp.elements.TtsStatement

final class TtsEndStatement = Impl::TtsEndStatement;
