// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `TtsStatement`.
 */

private import internal.TtsStatementImpl
import codeql.xpp.elements.Statement

final class TtsStatement = Impl::TtsStatement;
