// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `UnaryExpression`.
 */

private import internal.UnaryExpressionImpl
import codeql.xpp.elements.Expression

final class UnaryExpression = Impl::UnaryExpression;
