// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `UnaryMinusExpression`.
 */

private import internal.UnaryMinusExpressionImpl
import codeql.xpp.elements.UnaryExpression

final class UnaryMinusExpression = Impl::UnaryMinusExpression;
