// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `UncheckedStatement`.
 */

private import internal.UncheckedStatementImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Statement

final class UncheckedStatement = Impl::UncheckedStatement;
