// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `UnspecifiedElement`.
 */

private import internal.UnspecifiedElementImpl
import codeql.xpp.elements.Element
import codeql.xpp.elements.ErrorElement

/**
 * A node that could not be extracted, for example because of a syntax error.
 */
final class UnspecifiedElement = Impl::UnspecifiedElement;
