// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `UpdateStatement`.
 */

private import internal.UpdateStatementImpl
import codeql.xpp.elements.CrossCompany
import codeql.xpp.elements.Expression
import codeql.xpp.elements.FieldAssignment
import codeql.xpp.elements.JoinSpecification
import codeql.xpp.elements.Statement

final class UpdateStatement = Impl::UpdateStatement;
