// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `UsingStatement`.
 */

private import internal.UsingStatementImpl
import codeql.xpp.elements.Statement
import codeql.xpp.elements.VariableDeclaration

final class UsingStatement = Impl::UsingStatement;
