// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ValidTimeStateDate`.
 */

private import internal.ValidTimeStateDateImpl
import codeql.xpp.elements.ValidTimeState

final class ValidTimeStateDate = Impl::ValidTimeStateDate;
