// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ValidTimeState`.
 */

private import internal.ValidTimeStateImpl
import codeql.xpp.elements.Ast

final class ValidTimeState = Impl::ValidTimeState;
