// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `ValidTimeStateRange`.
 */

private import internal.ValidTimeStateRangeImpl
import codeql.xpp.elements.ValidTimeState

final class ValidTimeStateRange = Impl::ValidTimeStateRange;
