// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `VariableDeclaration`.
 */

private import internal.VariableDeclarationImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.LocalDeclaration

final class VariableDeclaration = Impl::VariableDeclaration;
