// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `VariableDeclarationInternal`.
 */

private import internal.VariableDeclarationInternalImpl
import codeql.xpp.elements.VariableDeclaration

final class VariableDeclarationInternal = Impl::VariableDeclarationInternal;
