// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `VarType`.
 */

private import internal.VarTypeImpl
import codeql.xpp.elements.XppType

final class VarType = Impl::VarType;
