// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `VoidType`.
 */

private import internal.VoidTypeImpl
import codeql.xpp.elements.XppType

final class VoidType = Impl::VoidType;
