// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `WhileStatement`.
 */

private import internal.WhileStatementImpl
import codeql.xpp.elements.Expression
import codeql.xpp.elements.Statement

final class WhileStatement = Impl::WhileStatement;
