// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `XppType`.
 */

private import internal.XppTypeImpl
import codeql.xpp.elements.Ast

final class XppType = Impl::XppType;
