// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `XppTypeCompilationUnit`.
 */

private import internal.XppTypeCompilationUnitImpl
import codeql.xpp.elements.CompilationUnit
import codeql.xpp.elements.XppType

final class XppTypeCompilationUnit = Impl::XppTypeCompilationUnit;
