// generated by xpp/tools/generate-schema.sh, do not edit
/**
 * This module provides the public class `XppTuple`.
 */

private import internal.XppTupleImpl
import codeql.xpp.elements.Locatable

/**
 * Base of the classes standing in for tuples in the compiler's AST.
 *
 * The X++ compiler uses CLR tuples for a handful of grouped values, such as a `catch`
 * together with its handler body. The schema has no tuple type, so the generator emits a
 * named class per tuple-valued property instead.
 */
final class XppTuple = Impl::XppTuple;
