name: PowerShell PR Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  powershell-pr-check:
    name: powershell-pr-check
    runs-on: windows-latest
    if: github.repository == 'microsoft/codeql'
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}
      - name: Setup CodeQL
        uses: ./.github/actions/fetch-codeql
        with:
          channel: release
      - name: Install PowerShell
        run: |
          $path = Split-Path (Get-Command codeql).Source
          ./powershell/build-win64.ps1 $path
      - name: Run QL tests
        run: |
          codeql test run --threads=0 powershell/ql/test
